os: linux
dist: trusty
language: java
jdk:
  - oraclejdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2

install:
  - mvn -B -f stats-loader/pom.xml dependency:resolve

script:
  - mvn -B -f stats-loader/pom.xml clean package

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
