os: linux
dist: trusty
language: java
jdk:
  - oraclejdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn -B -f stats-loader/pom.xml clean package

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push cpollet/covid19-stats-loader:latest
  - curl "https://webhook.cpollet.io/hooks/net.cpollet.covid19:stats-loader:update?token=$WEBHOOK_TOKEN"
