{
 "title": "Covid19",
 "time": { "from": "2020-02-23T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "canton",
    "query": "SHOW TAG VALUES FROM \"h2.Confirmed\" WITH KEY = \"canton\""
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
     "options": {
      "content": "# covid-19 stats\n## Data sources\n * [OpenZH](https://github.com/openZH/covid_19): hospitalisations data\n * [FOPH](https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/situation-schweiz-und-international.html): test data\n * [COVID-19 Re](https://github.com/covid-19-Re/dailyRe-Data): Re estimate\n * [bag_scrape](https://github.com/timoll/bag_scrape) - which is sourced from FOPH: everything else"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last update",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "measurement": "LastUpdate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "CH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "General",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Test",
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Positive",
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "positive" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Total cases",
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Prevalence",
     "measurement": "h2.Prevalence",
     "select": [
      [
       { "params": [ "prevalence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Re estimate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "low",
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_low" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    },
    {
     "alias": "median",
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    },
    {
     "alias": "high",
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_high" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Incidence / 14 days",
   "type": "gauge",
   "description": "cases  over the last 14 days / 100k population",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Death rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "death_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Cases / canton",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "!=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Incidence / 14 days / canton",
   "type": "grafana-piechart-panel",
   "description": "cases overs the last 14 days / 100k population",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "!=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Prevalence / canton",
   "type": "grafana-piechart-panel",
   "description": "cases / 100k population",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Prevalence",
     "select": [
      [
       { "params": [ "prevalence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "!=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Tests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "positive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "positive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "total, moving average 7d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "avg_tests_total_7d" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total, moving average 14d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "avg_tests_total_14d" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Positive tests ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "positive tests ratio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "posRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "positive tests ratio, moving average over 7 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "avg_posRatio_7d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "positive tests ratio, moving average over 14 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Tests",
     "select": [
      [
       { "params": [ "avg_posRatio_14d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "new cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "new cases, moving avg over 7 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "avg_7d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "new cases, moving avg over 14 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "avg_14d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Re estimate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_median" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    },
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_low" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Death rate",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "confirmed cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    },
    {
     "alias": "deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    },
    {
     "alias": "deaths / cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "death_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Incidence / 14 days",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "incidence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    }
   ]
  },
  {
   "title": "Incidence / 14 days",
   "type": "bargauge",
   "description": "cases  over the last 14 days / 100k population",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    },
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "!=", "value": "CH" }
     ]
    }
   ]
  },
  { "title": "Cases $canton", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Incidence / 14 days - $canton",
   "type": "bargauge",
   "description": "cases  over the last 14 days / 100k population",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=", "value": "CH" }
     ]
    },
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Cases - $canton",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Incidence / 14 days - $canton",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Prevalence - $canton",
   "type": "grafana-piechart-panel",
   "description": "cases / 100k population",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_canton",
     "groupBy": [
      { "params": [ "canton" ], "type": "tag" }
     ],
     "measurement": "h2.Prevalence",
     "select": [
      [
       { "params": [ "prevalence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Cases - $canton",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 55 },
   "repeat": "canton",
   "yaxes": [
    { "format": "none", "label": "Cases" }
   ],
   "targets": [
    {
     "alias": "total",
     "measurement": "h2.Confirmed",
     "query": "SELECT mean(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT difference(last(\"value\")) FROM \"cumulatedConfirmedForward\" WHERE (\"canton\" =~ /^$canton$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new, moving average over 7 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT last(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg_7d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new, moving average over 14 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT last(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg_14d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Cases - $canton",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none", "label": "Cases" }
   ],
   "targets": [
    {
     "alias": "total",
     "measurement": "h2.Confirmed",
     "query": "SELECT mean(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT difference(last(\"value\")) FROM \"cumulatedConfirmedForward\" WHERE (\"canton\" =~ /^$canton$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new, moving average over 7 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT last(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg_7d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new, moving average over 14 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT last(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg_14d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Cases - $canton",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "none", "label": "Cases" }
   ],
   "targets": [
    {
     "alias": "total",
     "measurement": "h2.Confirmed",
     "query": "SELECT mean(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT difference(last(\"value\")) FROM \"cumulatedConfirmedForward\" WHERE (\"canton\" =~ /^$canton$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new, moving average over 7 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT last(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg_7d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new, moving average over 14 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT last(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg_14d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Cases - $canton",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "none", "label": "Cases" }
   ],
   "targets": [
    {
     "alias": "total",
     "measurement": "h2.Confirmed",
     "query": "SELECT mean(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT difference(last(\"value\")) FROM \"cumulatedConfirmedForward\" WHERE (\"canton\" =~ /^$canton$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new, moving average over 7 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT last(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg_7d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new, moving average over 14 days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "query": "SELECT last(\"value\") FROM \"cumulatedConfirmedForward\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg_14d" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases - day $canton",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "repeat": "canton",
   "targets": [
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "7" ], "type": "moving_average" }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases - day $canton",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "7" ], "type": "moving_average" }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases - day $canton",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "7" ], "type": "moving_average" }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases - day $canton",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "7" ], "type": "moving_average" }
      ],
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of new cases / day - $canton",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 91 },
   "repeat": "canton",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of new cases / day - $canton",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of new cases / day - $canton",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of new cases / day - $canton",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  { "title": "Case / day $canton", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "New cases / day of the week - $canton",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "repeat": "canton",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed $tag_dayOfWeek",
     "groupBy": [
      { "params": [ "dayOfWeek" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases / day of the week - $canton",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed $tag_dayOfWeek",
     "groupBy": [
      { "params": [ "dayOfWeek" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases / day of the week - $canton",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed $tag_dayOfWeek",
     "groupBy": [
      { "params": [ "dayOfWeek" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases / day of the week - $canton",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed $tag_dayOfWeek",
     "groupBy": [
      { "params": [ "dayOfWeek" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases / day of week - $canton",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 111 },
   "repeat": "canton",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_dayOfWeek",
     "groupBy": [
      { "params": [ "dayOfWeek" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases / day of week - $canton",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 111 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_dayOfWeek",
     "groupBy": [
      { "params": [ "dayOfWeek" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases / day of week - $canton",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 111 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_dayOfWeek",
     "groupBy": [
      { "params": [ "dayOfWeek" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "New cases / day of week - $canton",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 111 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_dayOfWeek",
     "groupBy": [
      { "params": [ "dayOfWeek" ], "type": "tag" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  { "title": "Hospitalised $canton", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Hospitalised - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "repeat": "canton",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "hospitalised",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Hospitalized",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "delta",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Hospitalized",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Hospitalised - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "hospitalised",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Hospitalized",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "delta",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Hospitalized",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Hospitalised - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "hospitalised",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Hospitalized",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "delta",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Hospitalized",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Hospitalised - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "hospitalised",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Hospitalized",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "delta",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Hospitalized",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  { "title": "Deaths $canton", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Deaths - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "repeat": "canton",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "new",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Death rate - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "repeat": "canton",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "confirmed cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "deaths / cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "death_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Death rate - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "confirmed cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "deaths / cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "death_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Death rate - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "confirmed cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "deaths / cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "death_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Death rate - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "confirmed cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "deaths / cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Deaths",
     "select": [
      [
       { "params": [ "death_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  { "title": "Re $canton", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 } },
  {
   "title": "Re estimate - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "repeat": "canton",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_median" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_low" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Re estimate - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_median" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_low" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Re estimate - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_median" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_low" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Re estimate - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_median" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_low" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19re.Re",
     "select": [
      [
       { "params": [ "re_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  { "title": "Incidence $canton", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 } },
  {
   "title": "Incidence / 14 days - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
   "repeat": "canton",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "incidence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Incidence / 14 days - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "incidence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Incidence / 14 days - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "incidence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  },
  {
   "title": "Incidence / 14 days - $canton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 199 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "incidence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2.Confirmed",
     "select": [
      [
       { "params": [ "incidence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "canton", "operator": "=~", "value": "/^$canton$/" }
     ]
    }
   ]
  }
 ]
}