version: '2'
services:
  grafana:
    image: "grafana/grafana:latest"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - default

  influxdb:
    image: "library/influxdb:latest"
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - default

  stats-loader:
    image: "cpollet/covid19-stats-loader:latest"
    environment:
      - INFLUXDB_HOST=influxdb
      - SCHEDULED=true
    networks:
      - default

volumes:
  grafana-data:
  influxdb-data:
